import turtle
turtle.Screen().bgcolor("navy blue")
flexibility= turtle.Turtle()
flexibility.forward(100)
flexibility.left(120)
flexibility.forward(100)
flexibility.left(120)
flexibility.forward(100)
flexibility.penup()
flexibility.right(150)
flexibility.forward(50)
flexibility.pendown()
flexibility.right(90)
flexibility.forward(100)
flexibility.right(120)
flexibility.forward(100)
flexibility.right(120)
flexibility.forward(100)

turtle.done()