neha= ("Neha=29th of june")
print(neha)
meher= ("Meher=17th of januaray")
print(meher)
rishab= ("Rishab=27 of october")
print(rishab)
abhay= ("Abhay=25th of december")
print(abhay)
pranav= ("Pranav=19th of july")
print(pranav)